---
title: "Crecimiento del consumo de energia electrica por el uso de criptomonedas"
author: "Aitor-Parrilla_Moises-Berrios_Diego-DeSousa_Gabriela-Machado"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Parte I

### PLANTEAMIENTO DEL PROBLEMA

>El progresivo desarrollo tecnológico, particularmente en los últimos veinte años, ha tenido un gran impacto sobre la biósfera y la sociedad en general. Ahora que se encuentra socialmente, ante la transición del dinero físico al dinero digital, es preciso evaluar las consecuencias de un cambio tan significativo. 
>Lo cierto es que, si bien las criptomonedas brindan la oportunidad de acceder a un sistema transparente, descentralizado y seguro para efectuar transacciones, también representan un importante elemento a considerar cuando se refiere, al aumento del consumo eléctrico mundial. 
De acuerdo a la Oficina de Política, Ciencia y Tecnología (2022), perteneciente al departamento del gobierno de los Estados Unidos: 
>
>>*Casi todo el consumo de electricidad de los cripto activos es impulsado por los mecanismos de consenso: la tecnología de contabilidad distribuida (DLT) utilizada para minar y verificar los cripto activos. El mecanismo de consenso dominante se llama Prueba de Trabajo (PoW), que es utilizado por las cadenas de bloques Bitcoin y Ethereum. Bitcoin y Ether combinados representan más del 60% de la capitalización total del mercado de los cripto activos. El mecanismo PoW está diseñado para requerir más poder de cómputo a medida que más entidades intentan validar transacciones para obtener una pequeña comisión en monedas, y esta característica ayuda a desincentivar a los actores malintencionados de atacar la red. A partir de agosto de 2022, se estima que Bitcoin representa del 60% al 77% del consumo total de electricidad de los cripto activos a nivel mundial, y Ethereum representa del 20% al 39%.*
>
>La eficiencia energética de estas máquinas ha aumentado, no obstante, el consumo eléctrico continúa aumentando. Asimismo, esto implica grandes emisiones CO2, uno de los principales gases responsables del efecto invernadero. Según lo investigado por Apraez et al. (2022), el Bitcoin es un claro ejemplo del impacto ambiental de las criptomonedas: 
>
>> En  los  últimos  dos  años,  el  aumento  histórico  de bitcoin  ha  provocado  que  las emisiones aumenten en más de 40 millones de toneladas, lo que equivale a 8,9 millones de automóviles agregados a las calles, impulsando el calentamiento global por encima de 2°C (p. 4). 
>
>El impacto ambiental de estos cripto activos no es un factor que la mayoría de las personas consideran al momento de invertir, sin embargo, esto se debe en gran medida al desconocimiento y lo poco tangible que resulta dicho fenómeno. Asimismo, existen pocas fuentes que permitan establecer una relación entre el consumo eléctrico y las muchas criptomonedas en existencia. Por ende, el presente proyecto plantea realizar comparaciones entre el consumo energético y el mercado de las criptomonedas (valores y transacciones)



### PROPUESTA

>El presente documento propone del desarrollo de un proyecto con titulo "Crecimiento del consumo de energia electrica por el uso de criptomonedas" LOs datos a utilizar seran:
>
>1. Histórico de precios de criptomonedas. Este dataset, obtenido de Kaggle, contiene información sobre las principales criptomonedas en el mercado actual. 
>
>2. Uso energético per cápita (per_capita_energy_use). Our World Data se dedica a publicar datos relacionados a los principales problemas del mundo, siendo el alza en el consumo eléctrico uno de ellos. Dicho dataset incluye el uso energético mundial por persona hasta el año 2021.  

>Las bases de datos de criptomonedas poseen diez variables. Estas son: SNo, Name, Symbol, Date, High, Low, Open, Close, Volume y Marketcap. Mientras que per_capita_energy_use tiene cuatro variables: Entity, Code, Year y Primary energy consumption per capita (kWh/person). Para el propósito de este proyecto, se le dara prioridad a las variables relacionadas con el valor y volúmen de transacciones de criptomonedas, y también al consumo de energía per capita. Esto con la finalidad de establecer una relación que permita comprender -aunque de manera muy básica- el impacto de los cripto activos en términos ambientales.



### JUSTIFICACIÓN

>La orientación al progreso y al desarrollo tecnológico son dos aspectos que caracterizan a la sociedad contemporánea, no obstante, esto constituye un problema cuando se desestima el impacto ambiental de sus hazañas. A pesar de que las ventajas de las transacciones con criptomonedas son muchas y representan el futuro de la economía mundial, el alto costo energético es imposible de ignorar.
>
>En tal sentido, es preciso tomar conciencia, adoptar alternativas y realizar mejoras. El presente proyecto pretende dar un primer paso, aportando una visualización clave del problema que motive al usuario a seguir investigando y a tomar decisiones más conscientes al momento de invertir en activos digitales. 

### METODOLOGIA

>La metodologia a ser aplicada sera una de caracter cuantitativo y analisis confirmatorio , nuestro metodo de recoleccion de datos sera basado en documentos y registros adquiridos de las plataformas Kaggle y Our World in Data. Los analisis a realizar seran por metodo estadistico inferencial. Principalmente se hara uso de la correlacion y la regresion para demostrar o negar la hipotesis planteada. 
>
>Las herramientas a utilizar para la limpieza y manejo seran Rstudio con las librerias Tidyverse, ggplot2, gridExtra.
>Los pasos a seguir para cumplir el objetivo seran:
>             *Limpiar las bases de datos de cualquier dato que este por fuera de los años 2013 a 2021
>             *Calcular el promedio mundial de: numero de transacciones,valor de la moneda,consumo de energia per capita
>             *Visualizar graficamente estos crecimientos.
>             *Calcular la correlacion entre promedio mundial de transacciones,promedio mudial de valor y promedio mundial de consumo
>             *Graficar una relacion entre consumo de energia y valor de cripto conla intencion de mostrar graficamente la correlacion



## REFERENCIAS 

- [The White House. (2022, Septiembre 08). Climate and Energy Implications of Crypto-Assets in the United States.]( https://www.whitehouse.gov/ostp/news-updates/2022/09/08/fact-sheet-climate-and-energy-implications-of-crypto-assets-in-the-united-states/)
- [Apraez Muñoz, J. J., Guaitarilla Moncayo, D. F., & Muñoz Gómez, C. A. (2022). Análisis del impacto ambiental por el consumo energético en la producción del bitcoin a nivel mundial. LOGINN Investigación Científica Y Tecnológica, 6(2).]( https://doi.org/10.23850/25907441.4800)
- [Cryptocurrency Historical Prices | Kaggle](https://www.kaggle.com/datasets/sudalairajkumar/cryptocurrencypricehistory?resource=download)
- [Energy Production and Consumption - Our World in Data](https://ourworldindata.org/energy-production-consumption)
- [GitHub: Proyecto de Ciencia de datos](https://github.com/AitorParr/Ciencia-De-Datos/tree/main)
