---
title: "Crecimiento del consumo de energía eléctrica, con emisiones de CO2 por el uso de criptomoneda"
author: "Aitor-Parrilla_Moises-Berrios_Diego-DeSousa_Gabriela-Machado"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### PLANTEAMIENTO DEL PROBLEMA

>El progresivo desarrollo tecnológico, particularmente en los últimos veinte años, ha tenido un gran impacto sobre la biósfera y la sociedad en general. Actualmente, existe una transición del dinero físico al dinero digital, y se quiere evaluar su efecto en la sociedad y en el medio ambiente. Y si este proceso representa algun cambio significativo. 
>Las criptomonedas brindan la oportunidad de acceder a un sistema transparente, descentralizado y seguro para efectuar transacciones, que representan un importante elemento a considerar cuando se refiere, al aumento del consumo de la energia eléctrica mundial. 
De acuerdo a la Oficina de Política, Ciencia y Tecnología (2022), perteneciente al departamento del gobierno de los Estados Unidos: 
>
>>*Casi todo el consumo de electricidad de los cripto activos es impulsado por los mecanismos de consenso: la tecnología de contabilidad distribuida (DLT) utilizada para minar y verificar los cripto activos. El mecanismo de consenso dominante se llama Prueba de Trabajo (PoW), que es utilizado por las cadenas de bloques Bitcoin y Ethereum. Bitcoin y Ether combinados representan más del 60% de la capitalización total del mercado de los cripto activos. El mecanismo PoW está diseñado para requerir más poder de cómputo a medida que más entidades intentan validar transacciones para obtener una pequeña comisión en monedas, y esta característica ayuda a desincentivar a los actores malintencionados de atacar la red. A partir de agosto de 2022, se estima que Bitcoin representa del 60% al 77% del consumo total de electricidad de los cripto activos a nivel mundial, y Ethereum representa del 20% al 39%.*
>
>Pese a que la eficiencia energética de estas máquinas ha aumentado, el consumo eléctrico continúa incrementandose. Esto implica, que las grandes emisiones de CO2, principal gas responsable del efecto invernadero probablemente sean causados por el incremento del consumo de energía. Según lo investigado por Apraez et al. (2022), el Bitcoin es un claro ejemplo del impacto ambiental de las criptomonedas: 
>
>> En  los  últimos  dos  años,  el  aumento  histórico  de bitcoin  ha  provocado  que  las emisiones aumenten en más de 40 millones de toneladas, lo que equivale a 8,9 millones de automóviles agregados a las calles, impulsando el calentamiento global por encima de 2°C (p. 4). 
>
>El impacto ambiental de estos cripto activos no es un factor que las personas consideren al momento de invertir, esto se debe en gran medida al desconocimiento del consumo electrico, que se realiza durante los mecanismos de consenso y lo poco estudiado que resulta dicho fenómeno. Asimismo, existen pocas fuentes que permitan establecer una relación entre el consumo eléctrico y las muchas criptomonedas en existencia. Por ende, el presente proyecto plantea; realizar comparaciones entre el consumo energético y el mercado de las criptomonedas (valores y transacciones) y el desprendimiento de CO2 registrado.



### PROPUESTA

>El presente documento propone del desarrollo de un proyecto con titulo "Crecimiento del consumo de energía eléctrica y emisiones de CO2 por el uso de criptomoneda" que constará en un sistema a través del cuál se pueda visualizar gráficamente, el impacto del creciente uso de las criptomonedas, haciendo énfasis, en el aumento del consumo eléctrico y las emisiones de CO2. Tomando como referencia algunos de los países con mayores tasas de consumo y la principal criptomoneda del mercado: Bitcoin, dándole un enfoque ambiental a ésta propuesta, considerando que, a mayor valor de la criptomoneda, es mayor el consumo eléctrico.

### DESCRIPCION DE LOS DATOS

>1. Histórico de precios de criptomonedas. Este dataset, obtenido de Kaggle, contiene información sobre las principales criptomonedas en el mercado actual. 
>
>2. Uso energético per cápita (per_capita_energy_use). Our World Data se dedica a publicar datos relacionados a los principales problemas del mundo. Siendo el alza en el consumo eléctrico uno de ellos. Dicho dataset incluye el uso energético mundial por persona hasta el año 2021. 
>
>3. Emisiones de CO2 y otros gases invernaderos. Our World Data publicó este dataset en 2022, siendo un registro de las emisiones de carbono por país comenzando desde el año 1850.
>
>4. Huella de carbono y consumo de energía del Bitcoin. Dicho dataset, contenido en el repositorio académico de ScienceDirect, recopila las emisiones de carbono relacionadas al Bitcoin desde el 2021. 

### JUSTIFICACIÓN

>La orientación al progreso y al desarrollo tecnológico, son dos aspectos que caracterizan a la sociedad contemporánea, no obstante, esto constituye un problema cuando se desestima el impacto ambiental de su desarrollo. A pesar de que las ventajas transaccinales son muchas, trabajando con criptomonedas, y representan el futuro de la economía mundial. Tiene como consecuencia un alto costo energético, imposible de ignorar.
>
>En tal sentido, es preciso tomar conciencia, adoptar alternativas y realizar mejoras. El presente proyecto pretende dar un primer paso, aportando una visualización clave del problema que motive al usuario a seguir investigando y a tomar decisiones más conscientes al momento de invertir en activos digitales. 

### METODOLOGIA

>La metodologia a ser aplicada, es de caracter cuantitativo, y analisis confirmatorio. Este método pretende realizar una recoleccion de datos, basado en documentos y registros adquiridos de las plataformas Kaggle y Our World in Data. Los analisis a realizar serán efectuados por el método estadístico inferencial. Principalmente, mediante la correlacion y regresion para demostrar o negar la hipotesis planteada. 
>
>Las herramientas a utilizar para la limpieza y manejo seran Rstudio con las librerias Tidyverse, ggplot2, gridExtra.
>Los pasos a seguir para cumplir el objetivo, descritos a continuación:
>
>1. Limpiar las bases de datos de cualquier dato que este por fuera de los años 2013 a 2021.
>
>2. Calcular el promedio mundial de: numero de transacciones,valor de la moneda,consumo de energia per capita, Emisiones CO2, y Visualizar graficamente estos crecimientos.
>
>3. Calcular la correlación del promedio mundial de transacciones, promedio mundial de valor, promedio mundial de consumo y Emisiones CO2.
>
>4. Graficar una relación entre consumo de energia, valor de cripto, emsiones CO2 y Volume de transacciones con la intencion de mostrar graficamente la correlacion.



## REFERENCIAS 

- [The White House. (2022, Septiembre 08). Climate and Energy Implications of Crypto-Assets in the United States.]( https://www.whitehouse.gov/ostp/news-updates/2022/09/08/fact-sheet-climate-and-energy-implications-of-crypto-assets-in-the-united-states/)
- [Apraez Muñoz, J. J., Guaitarilla Moncayo, D. F., & Muñoz Gómez, C. A. (2022). Análisis del impacto ambiental por el consumo energético en la producción del bitcoin a nivel mundial. LOGINN Investigación Científica Y Tecnológica, 6(2).]( https://doi.org/10.23850/25907441.4800)
- [Cryptocurrency Historical Prices | Kaggle](https://www.kaggle.com/datasets/sudalairajkumar/cryptocurrencypricehistory?resource=download)
